### ISSUE TITLE
Funky elixir web server won't start

### ISSUE THREAD

**Issue by aolko** [ramyma/a8r8#22]
wsl2, mirrored mode
```
10:11:13.427 [error] Running ExSdWeb.Endpoint with Bandit 1.5.5 at http failed, port 4000 already in use
10:11:13.427 [notice] Application ex_sd exited: ExSd.Application.start(:normal, []) returned an error: shutdown: failed to start child: ExSdWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {ExSdWeb.Endpoint, :http}
        ** (EXIT) shutdown: failed to start child: :listener
            ** (EXIT) :eaddrinuse
** (exit) :terminating
    (kernel 10.0) application_controller.erl:511: :application_controller.call/2
    (kernel 10.0) application.erl:367: :application."-ensure_all_started/3-lc$^0/1-0-"/1
    (kernel 10.0) application.erl:367: :application.ensure_all_started/3
    (mix 1.17.1) lib/mix/tasks/app.start.ex:72: Mix.Tasks.App.Start.start/3
    (mix 1.17.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.1) lib/mix/tasks/run.ex:129: Mix.Tasks.Run.run/5
    (mix 1.17.1) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix 1.17.1) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
```
in NAT mode `localhost:4000` is inaccessible entirely (`connectionfailure`)

**Comment by ramyma** [comment]
By default it resolves with the WSL asigned address.

I suppose in mirrored mode you can set localhost with the appropriate port number under `user.sh`.

You'll have to uncomment the line for AUTO1111 if using Automatic1111 or Forge, and COMFY for ComfyUI.

Let me know how it goes, or if you need further clarification.
